// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface DBNotFoundOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.DBNotFound)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();
}
