// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * DBState db state
 * </pre>
 *
 * Protobuf enum {@code meta.DBState}
 */
public enum DBState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * RU read and update
   * </pre>
   *
   * <code>RU = 0;</code>
   */
  RU(0),
  /**
   * <pre>
   * RWU read, append write and update
   * </pre>
   *
   * <code>RWU = 1;</code>
   */
  RWU(1),
  ;

  /**
   * <pre>
   * RU read and update
   * </pre>
   *
   * <code>RU = 0;</code>
   */
  public static final int RU_VALUE = 0;
  /**
   * <pre>
   * RWU read, append write and update
   * </pre>
   *
   * <code>RWU = 1;</code>
   */
  public static final int RWU_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static DBState valueOf(int value) {
    return forNumber(value);
  }

  public static DBState forNumber(int value) {
    switch (value) {
      case 0: return RU;
      case 1: return RWU;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DBState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DBState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DBState>() {
          public DBState findValueByNumber(int number) {
            return DBState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return HyenaMetaPB.getDescriptor().getEnumTypes().get(1);
  }

  private static final DBState[] VALUES = values();

  public static DBState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DBState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:meta.DBState)
}

