// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface ErrResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ErrResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>optional bytes error = 2;</code>
   */
  boolean hasError();
  /**
   * <code>optional bytes error = 2;</code>
   */
  com.google.protobuf.ByteString getError();
}
