// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * ErrResponse error response
 * </pre>
 *
 * Protobuf type {@code rpc.ErrResponse}
 */
public  final class ErrResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.ErrResponse)
    ErrResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ErrResponse.newBuilder() to construct.
  private ErrResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErrResponse() {
    id_ = com.google.protobuf.ByteString.EMPTY;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ErrResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            id_ = input.readBytes();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            message_ = bs;
            break;
          }
          case 26: {
            io.aicloud.sdk.hyena.pb.NotLeader.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = notLeader_.toBuilder();
            }
            notLeader_ = input.readMessage(io.aicloud.sdk.hyena.pb.NotLeader.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(notLeader_);
              notLeader_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            io.aicloud.sdk.hyena.pb.DBNotFound.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = dbNotFound_.toBuilder();
            }
            dbNotFound_ = input.readMessage(io.aicloud.sdk.hyena.pb.DBNotFound.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dbNotFound_);
              dbNotFound_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            io.aicloud.sdk.hyena.pb.StaleEpoch.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
              subBuilder = staleEpoch_.toBuilder();
            }
            staleEpoch_ = input.readMessage(io.aicloud.sdk.hyena.pb.StaleEpoch.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(staleEpoch_);
              staleEpoch_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              subBuilder = serverIsBusy_.toBuilder();
            }
            serverIsBusy_ = input.readMessage(io.aicloud.sdk.hyena.pb.ServerIsBusy.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(serverIsBusy_);
              serverIsBusy_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          case 58: {
            io.aicloud.sdk.hyena.pb.StaleCommand.Builder subBuilder = null;
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
              subBuilder = staleCommand_.toBuilder();
            }
            staleCommand_ = input.readMessage(io.aicloud.sdk.hyena.pb.StaleCommand.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(staleCommand_);
              staleCommand_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000040;
            break;
          }
          case 66: {
            io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder subBuilder = null;
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
              subBuilder = storeNotMatch_.toBuilder();
            }
            storeNotMatch_ = input.readMessage(io.aicloud.sdk.hyena.pb.StoreNotMatch.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(storeNotMatch_);
              storeNotMatch_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000080;
            break;
          }
          case 74: {
            io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder subBuilder = null;
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
              subBuilder = raftEntryTooLarge_.toBuilder();
            }
            raftEntryTooLarge_ = input.readMessage(io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(raftEntryTooLarge_);
              raftEntryTooLarge_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000100;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_ErrResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_ErrResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.aicloud.sdk.hyena.pb.ErrResponse.class, io.aicloud.sdk.hyena.pb.ErrResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString id_;
  /**
   * <code>optional bytes id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bytes id = 1;</code>
   */
  public com.google.protobuf.ByteString getId() {
    return id_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>optional string message = 2;</code>
   */
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTLEADER_FIELD_NUMBER = 3;
  private io.aicloud.sdk.hyena.pb.NotLeader notLeader_;
  /**
   * <code>optional .rpc.NotLeader notLeader = 3;</code>
   */
  public boolean hasNotLeader() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .rpc.NotLeader notLeader = 3;</code>
   */
  public io.aicloud.sdk.hyena.pb.NotLeader getNotLeader() {
    return notLeader_ == null ? io.aicloud.sdk.hyena.pb.NotLeader.getDefaultInstance() : notLeader_;
  }
  /**
   * <code>optional .rpc.NotLeader notLeader = 3;</code>
   */
  public io.aicloud.sdk.hyena.pb.NotLeaderOrBuilder getNotLeaderOrBuilder() {
    return notLeader_ == null ? io.aicloud.sdk.hyena.pb.NotLeader.getDefaultInstance() : notLeader_;
  }

  public static final int DBNOTFOUND_FIELD_NUMBER = 4;
  private io.aicloud.sdk.hyena.pb.DBNotFound dbNotFound_;
  /**
   * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
   */
  public boolean hasDbNotFound() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
   */
  public io.aicloud.sdk.hyena.pb.DBNotFound getDbNotFound() {
    return dbNotFound_ == null ? io.aicloud.sdk.hyena.pb.DBNotFound.getDefaultInstance() : dbNotFound_;
  }
  /**
   * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
   */
  public io.aicloud.sdk.hyena.pb.DBNotFoundOrBuilder getDbNotFoundOrBuilder() {
    return dbNotFound_ == null ? io.aicloud.sdk.hyena.pb.DBNotFound.getDefaultInstance() : dbNotFound_;
  }

  public static final int STALEEPOCH_FIELD_NUMBER = 5;
  private io.aicloud.sdk.hyena.pb.StaleEpoch staleEpoch_;
  /**
   * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
   */
  public boolean hasStaleEpoch() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
   */
  public io.aicloud.sdk.hyena.pb.StaleEpoch getStaleEpoch() {
    return staleEpoch_ == null ? io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance() : staleEpoch_;
  }
  /**
   * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
   */
  public io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder getStaleEpochOrBuilder() {
    return staleEpoch_ == null ? io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance() : staleEpoch_;
  }

  public static final int SERVERISBUSY_FIELD_NUMBER = 6;
  private io.aicloud.sdk.hyena.pb.ServerIsBusy serverIsBusy_;
  /**
   * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
   */
  public boolean hasServerIsBusy() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
   */
  public io.aicloud.sdk.hyena.pb.ServerIsBusy getServerIsBusy() {
    return serverIsBusy_ == null ? io.aicloud.sdk.hyena.pb.ServerIsBusy.getDefaultInstance() : serverIsBusy_;
  }
  /**
   * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
   */
  public io.aicloud.sdk.hyena.pb.ServerIsBusyOrBuilder getServerIsBusyOrBuilder() {
    return serverIsBusy_ == null ? io.aicloud.sdk.hyena.pb.ServerIsBusy.getDefaultInstance() : serverIsBusy_;
  }

  public static final int STALECOMMAND_FIELD_NUMBER = 7;
  private io.aicloud.sdk.hyena.pb.StaleCommand staleCommand_;
  /**
   * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
   */
  public boolean hasStaleCommand() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
   */
  public io.aicloud.sdk.hyena.pb.StaleCommand getStaleCommand() {
    return staleCommand_ == null ? io.aicloud.sdk.hyena.pb.StaleCommand.getDefaultInstance() : staleCommand_;
  }
  /**
   * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
   */
  public io.aicloud.sdk.hyena.pb.StaleCommandOrBuilder getStaleCommandOrBuilder() {
    return staleCommand_ == null ? io.aicloud.sdk.hyena.pb.StaleCommand.getDefaultInstance() : staleCommand_;
  }

  public static final int STORENOTMATCH_FIELD_NUMBER = 8;
  private io.aicloud.sdk.hyena.pb.StoreNotMatch storeNotMatch_;
  /**
   * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
   */
  public boolean hasStoreNotMatch() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
   */
  public io.aicloud.sdk.hyena.pb.StoreNotMatch getStoreNotMatch() {
    return storeNotMatch_ == null ? io.aicloud.sdk.hyena.pb.StoreNotMatch.getDefaultInstance() : storeNotMatch_;
  }
  /**
   * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
   */
  public io.aicloud.sdk.hyena.pb.StoreNotMatchOrBuilder getStoreNotMatchOrBuilder() {
    return storeNotMatch_ == null ? io.aicloud.sdk.hyena.pb.StoreNotMatch.getDefaultInstance() : storeNotMatch_;
  }

  public static final int RAFTENTRYTOOLARGE_FIELD_NUMBER = 9;
  private io.aicloud.sdk.hyena.pb.RaftEntryTooLarge raftEntryTooLarge_;
  /**
   * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
   */
  public boolean hasRaftEntryTooLarge() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
   */
  public io.aicloud.sdk.hyena.pb.RaftEntryTooLarge getRaftEntryTooLarge() {
    return raftEntryTooLarge_ == null ? io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.getDefaultInstance() : raftEntryTooLarge_;
  }
  /**
   * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
   */
  public io.aicloud.sdk.hyena.pb.RaftEntryTooLargeOrBuilder getRaftEntryTooLargeOrBuilder() {
    return raftEntryTooLarge_ == null ? io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.getDefaultInstance() : raftEntryTooLarge_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getNotLeader());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getDbNotFound());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(5, getStaleEpoch());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeMessage(6, getServerIsBusy());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeMessage(7, getStaleCommand());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeMessage(8, getStoreNotMatch());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeMessage(9, getRaftEntryTooLarge());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNotLeader());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDbNotFound());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getStaleEpoch());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getServerIsBusy());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getStaleCommand());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getStoreNotMatch());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getRaftEntryTooLarge());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.aicloud.sdk.hyena.pb.ErrResponse)) {
      return super.equals(obj);
    }
    io.aicloud.sdk.hyena.pb.ErrResponse other = (io.aicloud.sdk.hyena.pb.ErrResponse) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && (hasMessage() == other.hasMessage());
    if (hasMessage()) {
      result = result && getMessage()
          .equals(other.getMessage());
    }
    result = result && (hasNotLeader() == other.hasNotLeader());
    if (hasNotLeader()) {
      result = result && getNotLeader()
          .equals(other.getNotLeader());
    }
    result = result && (hasDbNotFound() == other.hasDbNotFound());
    if (hasDbNotFound()) {
      result = result && getDbNotFound()
          .equals(other.getDbNotFound());
    }
    result = result && (hasStaleEpoch() == other.hasStaleEpoch());
    if (hasStaleEpoch()) {
      result = result && getStaleEpoch()
          .equals(other.getStaleEpoch());
    }
    result = result && (hasServerIsBusy() == other.hasServerIsBusy());
    if (hasServerIsBusy()) {
      result = result && getServerIsBusy()
          .equals(other.getServerIsBusy());
    }
    result = result && (hasStaleCommand() == other.hasStaleCommand());
    if (hasStaleCommand()) {
      result = result && getStaleCommand()
          .equals(other.getStaleCommand());
    }
    result = result && (hasStoreNotMatch() == other.hasStoreNotMatch());
    if (hasStoreNotMatch()) {
      result = result && getStoreNotMatch()
          .equals(other.getStoreNotMatch());
    }
    result = result && (hasRaftEntryTooLarge() == other.hasRaftEntryTooLarge());
    if (hasRaftEntryTooLarge()) {
      result = result && getRaftEntryTooLarge()
          .equals(other.getRaftEntryTooLarge());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (hasNotLeader()) {
      hash = (37 * hash) + NOTLEADER_FIELD_NUMBER;
      hash = (53 * hash) + getNotLeader().hashCode();
    }
    if (hasDbNotFound()) {
      hash = (37 * hash) + DBNOTFOUND_FIELD_NUMBER;
      hash = (53 * hash) + getDbNotFound().hashCode();
    }
    if (hasStaleEpoch()) {
      hash = (37 * hash) + STALEEPOCH_FIELD_NUMBER;
      hash = (53 * hash) + getStaleEpoch().hashCode();
    }
    if (hasServerIsBusy()) {
      hash = (37 * hash) + SERVERISBUSY_FIELD_NUMBER;
      hash = (53 * hash) + getServerIsBusy().hashCode();
    }
    if (hasStaleCommand()) {
      hash = (37 * hash) + STALECOMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getStaleCommand().hashCode();
    }
    if (hasStoreNotMatch()) {
      hash = (37 * hash) + STORENOTMATCH_FIELD_NUMBER;
      hash = (53 * hash) + getStoreNotMatch().hashCode();
    }
    if (hasRaftEntryTooLarge()) {
      hash = (37 * hash) + RAFTENTRYTOOLARGE_FIELD_NUMBER;
      hash = (53 * hash) + getRaftEntryTooLarge().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.ErrResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.aicloud.sdk.hyena.pb.ErrResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ErrResponse error response
   * </pre>
   *
   * Protobuf type {@code rpc.ErrResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.ErrResponse)
      io.aicloud.sdk.hyena.pb.ErrResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_ErrResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_ErrResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aicloud.sdk.hyena.pb.ErrResponse.class, io.aicloud.sdk.hyena.pb.ErrResponse.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.ErrResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNotLeaderFieldBuilder();
        getDbNotFoundFieldBuilder();
        getStaleEpochFieldBuilder();
        getServerIsBusyFieldBuilder();
        getStaleCommandFieldBuilder();
        getStoreNotMatchFieldBuilder();
        getRaftEntryTooLargeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (notLeaderBuilder_ == null) {
        notLeader_ = null;
      } else {
        notLeaderBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (dbNotFoundBuilder_ == null) {
        dbNotFound_ = null;
      } else {
        dbNotFoundBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (staleEpochBuilder_ == null) {
        staleEpoch_ = null;
      } else {
        staleEpochBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (serverIsBusyBuilder_ == null) {
        serverIsBusy_ = null;
      } else {
        serverIsBusyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (staleCommandBuilder_ == null) {
        staleCommand_ = null;
      } else {
        staleCommandBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (storeNotMatchBuilder_ == null) {
        storeNotMatch_ = null;
      } else {
        storeNotMatchBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (raftEntryTooLargeBuilder_ == null) {
        raftEntryTooLarge_ = null;
      } else {
        raftEntryTooLargeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_ErrResponse_descriptor;
    }

    public io.aicloud.sdk.hyena.pb.ErrResponse getDefaultInstanceForType() {
      return io.aicloud.sdk.hyena.pb.ErrResponse.getDefaultInstance();
    }

    public io.aicloud.sdk.hyena.pb.ErrResponse build() {
      io.aicloud.sdk.hyena.pb.ErrResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.aicloud.sdk.hyena.pb.ErrResponse buildPartial() {
      io.aicloud.sdk.hyena.pb.ErrResponse result = new io.aicloud.sdk.hyena.pb.ErrResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.message_ = message_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (notLeaderBuilder_ == null) {
        result.notLeader_ = notLeader_;
      } else {
        result.notLeader_ = notLeaderBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (dbNotFoundBuilder_ == null) {
        result.dbNotFound_ = dbNotFound_;
      } else {
        result.dbNotFound_ = dbNotFoundBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      if (staleEpochBuilder_ == null) {
        result.staleEpoch_ = staleEpoch_;
      } else {
        result.staleEpoch_ = staleEpochBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      if (serverIsBusyBuilder_ == null) {
        result.serverIsBusy_ = serverIsBusy_;
      } else {
        result.serverIsBusy_ = serverIsBusyBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      if (staleCommandBuilder_ == null) {
        result.staleCommand_ = staleCommand_;
      } else {
        result.staleCommand_ = staleCommandBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      if (storeNotMatchBuilder_ == null) {
        result.storeNotMatch_ = storeNotMatch_;
      } else {
        result.storeNotMatch_ = storeNotMatchBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      if (raftEntryTooLargeBuilder_ == null) {
        result.raftEntryTooLarge_ = raftEntryTooLarge_;
      } else {
        result.raftEntryTooLarge_ = raftEntryTooLargeBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.aicloud.sdk.hyena.pb.ErrResponse) {
        return mergeFrom((io.aicloud.sdk.hyena.pb.ErrResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.aicloud.sdk.hyena.pb.ErrResponse other) {
      if (other == io.aicloud.sdk.hyena.pb.ErrResponse.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000002;
        message_ = other.message_;
        onChanged();
      }
      if (other.hasNotLeader()) {
        mergeNotLeader(other.getNotLeader());
      }
      if (other.hasDbNotFound()) {
        mergeDbNotFound(other.getDbNotFound());
      }
      if (other.hasStaleEpoch()) {
        mergeStaleEpoch(other.getStaleEpoch());
      }
      if (other.hasServerIsBusy()) {
        mergeServerIsBusy(other.getServerIsBusy());
      }
      if (other.hasStaleCommand()) {
        mergeStaleCommand(other.getStaleCommand());
      }
      if (other.hasStoreNotMatch()) {
        mergeStoreNotMatch(other.getStoreNotMatch());
      }
      if (other.hasRaftEntryTooLarge()) {
        mergeRaftEntryTooLarge(other.getRaftEntryTooLarge());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.aicloud.sdk.hyena.pb.ErrResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.aicloud.sdk.hyena.pb.ErrResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder setId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }

    private io.aicloud.sdk.hyena.pb.NotLeader notLeader_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.NotLeader, io.aicloud.sdk.hyena.pb.NotLeader.Builder, io.aicloud.sdk.hyena.pb.NotLeaderOrBuilder> notLeaderBuilder_;
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public boolean hasNotLeader() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public io.aicloud.sdk.hyena.pb.NotLeader getNotLeader() {
      if (notLeaderBuilder_ == null) {
        return notLeader_ == null ? io.aicloud.sdk.hyena.pb.NotLeader.getDefaultInstance() : notLeader_;
      } else {
        return notLeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public Builder setNotLeader(io.aicloud.sdk.hyena.pb.NotLeader value) {
      if (notLeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        notLeader_ = value;
        onChanged();
      } else {
        notLeaderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public Builder setNotLeader(
        io.aicloud.sdk.hyena.pb.NotLeader.Builder builderForValue) {
      if (notLeaderBuilder_ == null) {
        notLeader_ = builderForValue.build();
        onChanged();
      } else {
        notLeaderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public Builder mergeNotLeader(io.aicloud.sdk.hyena.pb.NotLeader value) {
      if (notLeaderBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            notLeader_ != null &&
            notLeader_ != io.aicloud.sdk.hyena.pb.NotLeader.getDefaultInstance()) {
          notLeader_ =
            io.aicloud.sdk.hyena.pb.NotLeader.newBuilder(notLeader_).mergeFrom(value).buildPartial();
        } else {
          notLeader_ = value;
        }
        onChanged();
      } else {
        notLeaderBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public Builder clearNotLeader() {
      if (notLeaderBuilder_ == null) {
        notLeader_ = null;
        onChanged();
      } else {
        notLeaderBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public io.aicloud.sdk.hyena.pb.NotLeader.Builder getNotLeaderBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getNotLeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    public io.aicloud.sdk.hyena.pb.NotLeaderOrBuilder getNotLeaderOrBuilder() {
      if (notLeaderBuilder_ != null) {
        return notLeaderBuilder_.getMessageOrBuilder();
      } else {
        return notLeader_ == null ?
            io.aicloud.sdk.hyena.pb.NotLeader.getDefaultInstance() : notLeader_;
      }
    }
    /**
     * <code>optional .rpc.NotLeader notLeader = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.NotLeader, io.aicloud.sdk.hyena.pb.NotLeader.Builder, io.aicloud.sdk.hyena.pb.NotLeaderOrBuilder> 
        getNotLeaderFieldBuilder() {
      if (notLeaderBuilder_ == null) {
        notLeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.NotLeader, io.aicloud.sdk.hyena.pb.NotLeader.Builder, io.aicloud.sdk.hyena.pb.NotLeaderOrBuilder>(
                getNotLeader(),
                getParentForChildren(),
                isClean());
        notLeader_ = null;
      }
      return notLeaderBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.DBNotFound dbNotFound_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.DBNotFound, io.aicloud.sdk.hyena.pb.DBNotFound.Builder, io.aicloud.sdk.hyena.pb.DBNotFoundOrBuilder> dbNotFoundBuilder_;
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public boolean hasDbNotFound() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public io.aicloud.sdk.hyena.pb.DBNotFound getDbNotFound() {
      if (dbNotFoundBuilder_ == null) {
        return dbNotFound_ == null ? io.aicloud.sdk.hyena.pb.DBNotFound.getDefaultInstance() : dbNotFound_;
      } else {
        return dbNotFoundBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public Builder setDbNotFound(io.aicloud.sdk.hyena.pb.DBNotFound value) {
      if (dbNotFoundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dbNotFound_ = value;
        onChanged();
      } else {
        dbNotFoundBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public Builder setDbNotFound(
        io.aicloud.sdk.hyena.pb.DBNotFound.Builder builderForValue) {
      if (dbNotFoundBuilder_ == null) {
        dbNotFound_ = builderForValue.build();
        onChanged();
      } else {
        dbNotFoundBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public Builder mergeDbNotFound(io.aicloud.sdk.hyena.pb.DBNotFound value) {
      if (dbNotFoundBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            dbNotFound_ != null &&
            dbNotFound_ != io.aicloud.sdk.hyena.pb.DBNotFound.getDefaultInstance()) {
          dbNotFound_ =
            io.aicloud.sdk.hyena.pb.DBNotFound.newBuilder(dbNotFound_).mergeFrom(value).buildPartial();
        } else {
          dbNotFound_ = value;
        }
        onChanged();
      } else {
        dbNotFoundBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public Builder clearDbNotFound() {
      if (dbNotFoundBuilder_ == null) {
        dbNotFound_ = null;
        onChanged();
      } else {
        dbNotFoundBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public io.aicloud.sdk.hyena.pb.DBNotFound.Builder getDbNotFoundBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDbNotFoundFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    public io.aicloud.sdk.hyena.pb.DBNotFoundOrBuilder getDbNotFoundOrBuilder() {
      if (dbNotFoundBuilder_ != null) {
        return dbNotFoundBuilder_.getMessageOrBuilder();
      } else {
        return dbNotFound_ == null ?
            io.aicloud.sdk.hyena.pb.DBNotFound.getDefaultInstance() : dbNotFound_;
      }
    }
    /**
     * <code>optional .rpc.DBNotFound dbNotFound = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.DBNotFound, io.aicloud.sdk.hyena.pb.DBNotFound.Builder, io.aicloud.sdk.hyena.pb.DBNotFoundOrBuilder> 
        getDbNotFoundFieldBuilder() {
      if (dbNotFoundBuilder_ == null) {
        dbNotFoundBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.DBNotFound, io.aicloud.sdk.hyena.pb.DBNotFound.Builder, io.aicloud.sdk.hyena.pb.DBNotFoundOrBuilder>(
                getDbNotFound(),
                getParentForChildren(),
                isClean());
        dbNotFound_ = null;
      }
      return dbNotFoundBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.StaleEpoch staleEpoch_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StaleEpoch, io.aicloud.sdk.hyena.pb.StaleEpoch.Builder, io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder> staleEpochBuilder_;
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public boolean hasStaleEpoch() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleEpoch getStaleEpoch() {
      if (staleEpochBuilder_ == null) {
        return staleEpoch_ == null ? io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance() : staleEpoch_;
      } else {
        return staleEpochBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public Builder setStaleEpoch(io.aicloud.sdk.hyena.pb.StaleEpoch value) {
      if (staleEpochBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        staleEpoch_ = value;
        onChanged();
      } else {
        staleEpochBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public Builder setStaleEpoch(
        io.aicloud.sdk.hyena.pb.StaleEpoch.Builder builderForValue) {
      if (staleEpochBuilder_ == null) {
        staleEpoch_ = builderForValue.build();
        onChanged();
      } else {
        staleEpochBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public Builder mergeStaleEpoch(io.aicloud.sdk.hyena.pb.StaleEpoch value) {
      if (staleEpochBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            staleEpoch_ != null &&
            staleEpoch_ != io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance()) {
          staleEpoch_ =
            io.aicloud.sdk.hyena.pb.StaleEpoch.newBuilder(staleEpoch_).mergeFrom(value).buildPartial();
        } else {
          staleEpoch_ = value;
        }
        onChanged();
      } else {
        staleEpochBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public Builder clearStaleEpoch() {
      if (staleEpochBuilder_ == null) {
        staleEpoch_ = null;
        onChanged();
      } else {
        staleEpochBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleEpoch.Builder getStaleEpochBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getStaleEpochFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder getStaleEpochOrBuilder() {
      if (staleEpochBuilder_ != null) {
        return staleEpochBuilder_.getMessageOrBuilder();
      } else {
        return staleEpoch_ == null ?
            io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance() : staleEpoch_;
      }
    }
    /**
     * <code>optional .rpc.StaleEpoch staleEpoch = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StaleEpoch, io.aicloud.sdk.hyena.pb.StaleEpoch.Builder, io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder> 
        getStaleEpochFieldBuilder() {
      if (staleEpochBuilder_ == null) {
        staleEpochBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.StaleEpoch, io.aicloud.sdk.hyena.pb.StaleEpoch.Builder, io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder>(
                getStaleEpoch(),
                getParentForChildren(),
                isClean());
        staleEpoch_ = null;
      }
      return staleEpochBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.ServerIsBusy serverIsBusy_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.ServerIsBusy, io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder, io.aicloud.sdk.hyena.pb.ServerIsBusyOrBuilder> serverIsBusyBuilder_;
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public boolean hasServerIsBusy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public io.aicloud.sdk.hyena.pb.ServerIsBusy getServerIsBusy() {
      if (serverIsBusyBuilder_ == null) {
        return serverIsBusy_ == null ? io.aicloud.sdk.hyena.pb.ServerIsBusy.getDefaultInstance() : serverIsBusy_;
      } else {
        return serverIsBusyBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public Builder setServerIsBusy(io.aicloud.sdk.hyena.pb.ServerIsBusy value) {
      if (serverIsBusyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverIsBusy_ = value;
        onChanged();
      } else {
        serverIsBusyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public Builder setServerIsBusy(
        io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder builderForValue) {
      if (serverIsBusyBuilder_ == null) {
        serverIsBusy_ = builderForValue.build();
        onChanged();
      } else {
        serverIsBusyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public Builder mergeServerIsBusy(io.aicloud.sdk.hyena.pb.ServerIsBusy value) {
      if (serverIsBusyBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            serverIsBusy_ != null &&
            serverIsBusy_ != io.aicloud.sdk.hyena.pb.ServerIsBusy.getDefaultInstance()) {
          serverIsBusy_ =
            io.aicloud.sdk.hyena.pb.ServerIsBusy.newBuilder(serverIsBusy_).mergeFrom(value).buildPartial();
        } else {
          serverIsBusy_ = value;
        }
        onChanged();
      } else {
        serverIsBusyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public Builder clearServerIsBusy() {
      if (serverIsBusyBuilder_ == null) {
        serverIsBusy_ = null;
        onChanged();
      } else {
        serverIsBusyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder getServerIsBusyBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getServerIsBusyFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    public io.aicloud.sdk.hyena.pb.ServerIsBusyOrBuilder getServerIsBusyOrBuilder() {
      if (serverIsBusyBuilder_ != null) {
        return serverIsBusyBuilder_.getMessageOrBuilder();
      } else {
        return serverIsBusy_ == null ?
            io.aicloud.sdk.hyena.pb.ServerIsBusy.getDefaultInstance() : serverIsBusy_;
      }
    }
    /**
     * <code>optional .rpc.ServerIsBusy serverIsBusy = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.ServerIsBusy, io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder, io.aicloud.sdk.hyena.pb.ServerIsBusyOrBuilder> 
        getServerIsBusyFieldBuilder() {
      if (serverIsBusyBuilder_ == null) {
        serverIsBusyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.ServerIsBusy, io.aicloud.sdk.hyena.pb.ServerIsBusy.Builder, io.aicloud.sdk.hyena.pb.ServerIsBusyOrBuilder>(
                getServerIsBusy(),
                getParentForChildren(),
                isClean());
        serverIsBusy_ = null;
      }
      return serverIsBusyBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.StaleCommand staleCommand_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StaleCommand, io.aicloud.sdk.hyena.pb.StaleCommand.Builder, io.aicloud.sdk.hyena.pb.StaleCommandOrBuilder> staleCommandBuilder_;
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public boolean hasStaleCommand() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleCommand getStaleCommand() {
      if (staleCommandBuilder_ == null) {
        return staleCommand_ == null ? io.aicloud.sdk.hyena.pb.StaleCommand.getDefaultInstance() : staleCommand_;
      } else {
        return staleCommandBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public Builder setStaleCommand(io.aicloud.sdk.hyena.pb.StaleCommand value) {
      if (staleCommandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        staleCommand_ = value;
        onChanged();
      } else {
        staleCommandBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public Builder setStaleCommand(
        io.aicloud.sdk.hyena.pb.StaleCommand.Builder builderForValue) {
      if (staleCommandBuilder_ == null) {
        staleCommand_ = builderForValue.build();
        onChanged();
      } else {
        staleCommandBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public Builder mergeStaleCommand(io.aicloud.sdk.hyena.pb.StaleCommand value) {
      if (staleCommandBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            staleCommand_ != null &&
            staleCommand_ != io.aicloud.sdk.hyena.pb.StaleCommand.getDefaultInstance()) {
          staleCommand_ =
            io.aicloud.sdk.hyena.pb.StaleCommand.newBuilder(staleCommand_).mergeFrom(value).buildPartial();
        } else {
          staleCommand_ = value;
        }
        onChanged();
      } else {
        staleCommandBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public Builder clearStaleCommand() {
      if (staleCommandBuilder_ == null) {
        staleCommand_ = null;
        onChanged();
      } else {
        staleCommandBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleCommand.Builder getStaleCommandBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getStaleCommandFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    public io.aicloud.sdk.hyena.pb.StaleCommandOrBuilder getStaleCommandOrBuilder() {
      if (staleCommandBuilder_ != null) {
        return staleCommandBuilder_.getMessageOrBuilder();
      } else {
        return staleCommand_ == null ?
            io.aicloud.sdk.hyena.pb.StaleCommand.getDefaultInstance() : staleCommand_;
      }
    }
    /**
     * <code>optional .rpc.StaleCommand staleCommand = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StaleCommand, io.aicloud.sdk.hyena.pb.StaleCommand.Builder, io.aicloud.sdk.hyena.pb.StaleCommandOrBuilder> 
        getStaleCommandFieldBuilder() {
      if (staleCommandBuilder_ == null) {
        staleCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.StaleCommand, io.aicloud.sdk.hyena.pb.StaleCommand.Builder, io.aicloud.sdk.hyena.pb.StaleCommandOrBuilder>(
                getStaleCommand(),
                getParentForChildren(),
                isClean());
        staleCommand_ = null;
      }
      return staleCommandBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.StoreNotMatch storeNotMatch_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StoreNotMatch, io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder, io.aicloud.sdk.hyena.pb.StoreNotMatchOrBuilder> storeNotMatchBuilder_;
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public boolean hasStoreNotMatch() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public io.aicloud.sdk.hyena.pb.StoreNotMatch getStoreNotMatch() {
      if (storeNotMatchBuilder_ == null) {
        return storeNotMatch_ == null ? io.aicloud.sdk.hyena.pb.StoreNotMatch.getDefaultInstance() : storeNotMatch_;
      } else {
        return storeNotMatchBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public Builder setStoreNotMatch(io.aicloud.sdk.hyena.pb.StoreNotMatch value) {
      if (storeNotMatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        storeNotMatch_ = value;
        onChanged();
      } else {
        storeNotMatchBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public Builder setStoreNotMatch(
        io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder builderForValue) {
      if (storeNotMatchBuilder_ == null) {
        storeNotMatch_ = builderForValue.build();
        onChanged();
      } else {
        storeNotMatchBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public Builder mergeStoreNotMatch(io.aicloud.sdk.hyena.pb.StoreNotMatch value) {
      if (storeNotMatchBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080) &&
            storeNotMatch_ != null &&
            storeNotMatch_ != io.aicloud.sdk.hyena.pb.StoreNotMatch.getDefaultInstance()) {
          storeNotMatch_ =
            io.aicloud.sdk.hyena.pb.StoreNotMatch.newBuilder(storeNotMatch_).mergeFrom(value).buildPartial();
        } else {
          storeNotMatch_ = value;
        }
        onChanged();
      } else {
        storeNotMatchBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public Builder clearStoreNotMatch() {
      if (storeNotMatchBuilder_ == null) {
        storeNotMatch_ = null;
        onChanged();
      } else {
        storeNotMatchBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder getStoreNotMatchBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getStoreNotMatchFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    public io.aicloud.sdk.hyena.pb.StoreNotMatchOrBuilder getStoreNotMatchOrBuilder() {
      if (storeNotMatchBuilder_ != null) {
        return storeNotMatchBuilder_.getMessageOrBuilder();
      } else {
        return storeNotMatch_ == null ?
            io.aicloud.sdk.hyena.pb.StoreNotMatch.getDefaultInstance() : storeNotMatch_;
      }
    }
    /**
     * <code>optional .rpc.StoreNotMatch storeNotMatch = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.StoreNotMatch, io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder, io.aicloud.sdk.hyena.pb.StoreNotMatchOrBuilder> 
        getStoreNotMatchFieldBuilder() {
      if (storeNotMatchBuilder_ == null) {
        storeNotMatchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.StoreNotMatch, io.aicloud.sdk.hyena.pb.StoreNotMatch.Builder, io.aicloud.sdk.hyena.pb.StoreNotMatchOrBuilder>(
                getStoreNotMatch(),
                getParentForChildren(),
                isClean());
        storeNotMatch_ = null;
      }
      return storeNotMatchBuilder_;
    }

    private io.aicloud.sdk.hyena.pb.RaftEntryTooLarge raftEntryTooLarge_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.RaftEntryTooLarge, io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder, io.aicloud.sdk.hyena.pb.RaftEntryTooLargeOrBuilder> raftEntryTooLargeBuilder_;
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public boolean hasRaftEntryTooLarge() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public io.aicloud.sdk.hyena.pb.RaftEntryTooLarge getRaftEntryTooLarge() {
      if (raftEntryTooLargeBuilder_ == null) {
        return raftEntryTooLarge_ == null ? io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.getDefaultInstance() : raftEntryTooLarge_;
      } else {
        return raftEntryTooLargeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public Builder setRaftEntryTooLarge(io.aicloud.sdk.hyena.pb.RaftEntryTooLarge value) {
      if (raftEntryTooLargeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        raftEntryTooLarge_ = value;
        onChanged();
      } else {
        raftEntryTooLargeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public Builder setRaftEntryTooLarge(
        io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder builderForValue) {
      if (raftEntryTooLargeBuilder_ == null) {
        raftEntryTooLarge_ = builderForValue.build();
        onChanged();
      } else {
        raftEntryTooLargeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public Builder mergeRaftEntryTooLarge(io.aicloud.sdk.hyena.pb.RaftEntryTooLarge value) {
      if (raftEntryTooLargeBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100) &&
            raftEntryTooLarge_ != null &&
            raftEntryTooLarge_ != io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.getDefaultInstance()) {
          raftEntryTooLarge_ =
            io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.newBuilder(raftEntryTooLarge_).mergeFrom(value).buildPartial();
        } else {
          raftEntryTooLarge_ = value;
        }
        onChanged();
      } else {
        raftEntryTooLargeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public Builder clearRaftEntryTooLarge() {
      if (raftEntryTooLargeBuilder_ == null) {
        raftEntryTooLarge_ = null;
        onChanged();
      } else {
        raftEntryTooLargeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder getRaftEntryTooLargeBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getRaftEntryTooLargeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    public io.aicloud.sdk.hyena.pb.RaftEntryTooLargeOrBuilder getRaftEntryTooLargeOrBuilder() {
      if (raftEntryTooLargeBuilder_ != null) {
        return raftEntryTooLargeBuilder_.getMessageOrBuilder();
      } else {
        return raftEntryTooLarge_ == null ?
            io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.getDefaultInstance() : raftEntryTooLarge_;
      }
    }
    /**
     * <code>optional .rpc.RaftEntryTooLarge raftEntryTooLarge = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.RaftEntryTooLarge, io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder, io.aicloud.sdk.hyena.pb.RaftEntryTooLargeOrBuilder> 
        getRaftEntryTooLargeFieldBuilder() {
      if (raftEntryTooLargeBuilder_ == null) {
        raftEntryTooLargeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.RaftEntryTooLarge, io.aicloud.sdk.hyena.pb.RaftEntryTooLarge.Builder, io.aicloud.sdk.hyena.pb.RaftEntryTooLargeOrBuilder>(
                getRaftEntryTooLarge(),
                getParentForChildren(),
                isClean());
        raftEntryTooLarge_ = null;
      }
      return raftEntryTooLargeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.ErrResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.ErrResponse)
  private static final io.aicloud.sdk.hyena.pb.ErrResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.aicloud.sdk.hyena.pb.ErrResponse();
  }

  public static io.aicloud.sdk.hyena.pb.ErrResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ErrResponse>
      PARSER = new com.google.protobuf.AbstractParser<ErrResponse>() {
    public ErrResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ErrResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ErrResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErrResponse> getParserForType() {
    return PARSER;
  }

  public io.aicloud.sdk.hyena.pb.ErrResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

