// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface InsertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.InsertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>repeated float xbs = 2;</code>
   */
  java.util.List<java.lang.Float> getXbsList();
  /**
   * <code>repeated float xbs = 2;</code>
   */
  int getXbsCount();
  /**
   * <code>repeated float xbs = 2;</code>
   */
  float getXbs(int index);

  /**
   * <code>repeated int64 ids = 3;</code>
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated int64 ids = 3;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated int64 ids = 3;</code>
   */
  long getIds(int index);

  /**
   * <code>optional int64 offset = 4;</code>
   */
  boolean hasOffset();
  /**
   * <code>optional int64 offset = 4;</code>
   */
  long getOffset();
}
