// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * InsertRequest insert request
 * </pre>
 *
 * Protobuf type {@code rpc.InsertRequest}
 */
public  final class InsertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.InsertRequest)
    InsertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InsertRequest.newBuilder() to construct.
  private InsertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InsertRequest() {
    id_ = com.google.protobuf.ByteString.EMPTY;
    xbs_ = java.util.Collections.emptyList();
    ids_ = java.util.Collections.emptyList();
    offset_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InsertRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            id_ = input.readBytes();
            break;
          }
          case 21: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              xbs_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            xbs_.add(input.readFloat());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              xbs_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              xbs_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              ids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            ids_.add(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              ids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              ids_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            bitField0_ |= 0x00000002;
            offset_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        xbs_ = java.util.Collections.unmodifiableList(xbs_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        ids_ = java.util.Collections.unmodifiableList(ids_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_InsertRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_InsertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.aicloud.sdk.hyena.pb.InsertRequest.class, io.aicloud.sdk.hyena.pb.InsertRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString id_;
  /**
   * <code>optional bytes id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bytes id = 1;</code>
   */
  public com.google.protobuf.ByteString getId() {
    return id_;
  }

  public static final int XBS_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Float> xbs_;
  /**
   * <code>repeated float xbs = 2;</code>
   */
  public java.util.List<java.lang.Float>
      getXbsList() {
    return xbs_;
  }
  /**
   * <code>repeated float xbs = 2;</code>
   */
  public int getXbsCount() {
    return xbs_.size();
  }
  /**
   * <code>repeated float xbs = 2;</code>
   */
  public float getXbs(int index) {
    return xbs_.get(index);
  }

  public static final int IDS_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Long> ids_;
  /**
   * <code>repeated int64 ids = 3;</code>
   */
  public java.util.List<java.lang.Long>
      getIdsList() {
    return ids_;
  }
  /**
   * <code>repeated int64 ids = 3;</code>
   */
  public int getIdsCount() {
    return ids_.size();
  }
  /**
   * <code>repeated int64 ids = 3;</code>
   */
  public long getIds(int index) {
    return ids_.get(index);
  }

  public static final int OFFSET_FIELD_NUMBER = 4;
  private long offset_;
  /**
   * <code>optional int64 offset = 4;</code>
   */
  public boolean hasOffset() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 offset = 4;</code>
   */
  public long getOffset() {
    return offset_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, id_);
    }
    for (int i = 0; i < xbs_.size(); i++) {
      output.writeFloat(2, xbs_.get(i));
    }
    for (int i = 0; i < ids_.size(); i++) {
      output.writeInt64(3, ids_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(4, offset_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, id_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getXbsList().size();
      size += dataSize;
      size += 1 * getXbsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ids_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(ids_.get(i));
      }
      size += dataSize;
      size += 1 * getIdsList().size();
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, offset_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.aicloud.sdk.hyena.pb.InsertRequest)) {
      return super.equals(obj);
    }
    io.aicloud.sdk.hyena.pb.InsertRequest other = (io.aicloud.sdk.hyena.pb.InsertRequest) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && getXbsList()
        .equals(other.getXbsList());
    result = result && getIdsList()
        .equals(other.getIdsList());
    result = result && (hasOffset() == other.hasOffset());
    if (hasOffset()) {
      result = result && (getOffset()
          == other.getOffset());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (getXbsCount() > 0) {
      hash = (37 * hash) + XBS_FIELD_NUMBER;
      hash = (53 * hash) + getXbsList().hashCode();
    }
    if (getIdsCount() > 0) {
      hash = (37 * hash) + IDS_FIELD_NUMBER;
      hash = (53 * hash) + getIdsList().hashCode();
    }
    if (hasOffset()) {
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.InsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.aicloud.sdk.hyena.pb.InsertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * InsertRequest insert request
   * </pre>
   *
   * Protobuf type {@code rpc.InsertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.InsertRequest)
      io.aicloud.sdk.hyena.pb.InsertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_InsertRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_InsertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aicloud.sdk.hyena.pb.InsertRequest.class, io.aicloud.sdk.hyena.pb.InsertRequest.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.InsertRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      xbs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      ids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      offset_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_InsertRequest_descriptor;
    }

    public io.aicloud.sdk.hyena.pb.InsertRequest getDefaultInstanceForType() {
      return io.aicloud.sdk.hyena.pb.InsertRequest.getDefaultInstance();
    }

    public io.aicloud.sdk.hyena.pb.InsertRequest build() {
      io.aicloud.sdk.hyena.pb.InsertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.aicloud.sdk.hyena.pb.InsertRequest buildPartial() {
      io.aicloud.sdk.hyena.pb.InsertRequest result = new io.aicloud.sdk.hyena.pb.InsertRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        xbs_ = java.util.Collections.unmodifiableList(xbs_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.xbs_ = xbs_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        ids_ = java.util.Collections.unmodifiableList(ids_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.ids_ = ids_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000002;
      }
      result.offset_ = offset_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.aicloud.sdk.hyena.pb.InsertRequest) {
        return mergeFrom((io.aicloud.sdk.hyena.pb.InsertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.aicloud.sdk.hyena.pb.InsertRequest other) {
      if (other == io.aicloud.sdk.hyena.pb.InsertRequest.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (!other.xbs_.isEmpty()) {
        if (xbs_.isEmpty()) {
          xbs_ = other.xbs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureXbsIsMutable();
          xbs_.addAll(other.xbs_);
        }
        onChanged();
      }
      if (!other.ids_.isEmpty()) {
        if (ids_.isEmpty()) {
          ids_ = other.ids_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureIdsIsMutable();
          ids_.addAll(other.ids_);
        }
        onChanged();
      }
      if (other.hasOffset()) {
        setOffset(other.getOffset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.aicloud.sdk.hyena.pb.InsertRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.aicloud.sdk.hyena.pb.InsertRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder setId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> xbs_ = java.util.Collections.emptyList();
    private void ensureXbsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        xbs_ = new java.util.ArrayList<java.lang.Float>(xbs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getXbsList() {
      return java.util.Collections.unmodifiableList(xbs_);
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public int getXbsCount() {
      return xbs_.size();
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public float getXbs(int index) {
      return xbs_.get(index);
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public Builder setXbs(
        int index, float value) {
      ensureXbsIsMutable();
      xbs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public Builder addXbs(float value) {
      ensureXbsIsMutable();
      xbs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public Builder addAllXbs(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureXbsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, xbs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float xbs = 2;</code>
     */
    public Builder clearXbs() {
      xbs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> ids_ = java.util.Collections.emptyList();
    private void ensureIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        ids_ = new java.util.ArrayList<java.lang.Long>(ids_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getIdsList() {
      return java.util.Collections.unmodifiableList(ids_);
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public long getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public Builder setIds(
        int index, long value) {
      ensureIdsIsMutable();
      ids_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public Builder addIds(long value) {
      ensureIdsIsMutable();
      ids_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public Builder addAllIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ids_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 3;</code>
     */
    public Builder clearIds() {
      ids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>optional int64 offset = 4;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 offset = 4;</code>
     */
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>optional int64 offset = 4;</code>
     */
    public Builder setOffset(long value) {
      bitField0_ |= 0x00000008;
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 offset = 4;</code>
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000008);
      offset_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.InsertRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.InsertRequest)
  private static final io.aicloud.sdk.hyena.pb.InsertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.aicloud.sdk.hyena.pb.InsertRequest();
  }

  public static io.aicloud.sdk.hyena.pb.InsertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<InsertRequest>
      PARSER = new com.google.protobuf.AbstractParser<InsertRequest>() {
    public InsertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InsertRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InsertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InsertRequest> getParserForType() {
    return PARSER;
  }

  public io.aicloud.sdk.hyena.pb.InsertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

