// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

public interface LabelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.Label)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>optional string key = 1;</code>
   */
  String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>optional string value = 2;</code>
   */
  String getValue();
  /**
   * <code>optional string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
