// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface NotLeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.NotLeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional .meta.Peer leader = 2;</code>
   */
  boolean hasLeader();
  /**
   * <code>optional .meta.Peer leader = 2;</code>
   */
  io.aicloud.sdk.hyena.pb.Peer getLeader();
  /**
   * <code>optional .meta.Peer leader = 2;</code>
   */
  io.aicloud.sdk.hyena.pb.PeerOrBuilder getLeaderOrBuilder();
}
