// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

public interface PeerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.Peer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional uint64 storeID = 2;</code>
   */
  boolean hasStoreID();
  /**
   * <code>optional uint64 storeID = 2;</code>
   */
  long getStoreID();
}
