// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>repeated float distances = 2;</code>
   */
  java.util.List<java.lang.Float> getDistancesList();
  /**
   * <code>repeated float distances = 2;</code>
   */
  int getDistancesCount();
  /**
   * <code>repeated float distances = 2;</code>
   */
  float getDistances(int index);

  /**
   * <code>repeated int64 xids = 3;</code>
   */
  java.util.List<java.lang.Long> getXidsList();
  /**
   * <code>repeated int64 xids = 3;</code>
   */
  int getXidsCount();
  /**
   * <code>repeated int64 xids = 3;</code>
   */
  long getXids(int index);

  /**
   * <code>optional uint64 db = 4;</code>
   */
  boolean hasDb();
  /**
   * <code>optional uint64 db = 4;</code>
   */
  long getDb();

  /**
   * <code>optional bool searchNext = 5;</code>
   */
  boolean hasSearchNext();
  /**
   * <code>optional bool searchNext = 5;</code>
   */
  boolean getSearchNext();
}
