// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>optional uint64 db = 2;</code>
   */
  boolean hasDb();
  /**
   * <code>optional uint64 db = 2;</code>
   */
  long getDb();

  /**
   * <code>repeated float xq = 3;</code>
   */
  java.util.List<Float> getXqList();
  /**
   * <code>repeated float xq = 3;</code>
   */
  int getXqCount();
  /**
   * <code>repeated float xq = 3;</code>
   */
  float getXq(int index);

  /**
   * <code>optional int64 offset = 4;</code>
   */
  boolean hasOffset();
  /**
   * <code>optional int64 offset = 4;</code>
   */
  long getOffset();
}
