// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * SearchResponse search response
 * </pre>
 *
 * Protobuf type {@code rpc.SearchResponse}
 */
public  final class SearchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.SearchResponse)
    SearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchResponse.newBuilder() to construct.
  private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchResponse() {
    id_ = com.google.protobuf.ByteString.EMPTY;
    distances_ = java.util.Collections.emptyList();
    xids_ = java.util.Collections.emptyList();
    db_ = 0L;
    searchNext_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            id_ = input.readBytes();
            break;
          }
          case 21: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              distances_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            distances_.add(input.readFloat());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              distances_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              distances_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              xids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            xids_.add(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              xids_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              xids_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            bitField0_ |= 0x00000002;
            db_ = input.readUInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000004;
            searchNext_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        distances_ = java.util.Collections.unmodifiableList(distances_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        xids_ = java.util.Collections.unmodifiableList(xids_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_SearchResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_SearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.aicloud.sdk.hyena.pb.SearchResponse.class, io.aicloud.sdk.hyena.pb.SearchResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString id_;
  /**
   * <code>optional bytes id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bytes id = 1;</code>
   */
  public com.google.protobuf.ByteString getId() {
    return id_;
  }

  public static final int DISTANCES_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Float> distances_;
  /**
   * <code>repeated float distances = 2;</code>
   */
  public java.util.List<java.lang.Float>
      getDistancesList() {
    return distances_;
  }
  /**
   * <code>repeated float distances = 2;</code>
   */
  public int getDistancesCount() {
    return distances_.size();
  }
  /**
   * <code>repeated float distances = 2;</code>
   */
  public float getDistances(int index) {
    return distances_.get(index);
  }

  public static final int XIDS_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Long> xids_;
  /**
   * <code>repeated int64 xids = 3;</code>
   */
  public java.util.List<java.lang.Long>
      getXidsList() {
    return xids_;
  }
  /**
   * <code>repeated int64 xids = 3;</code>
   */
  public int getXidsCount() {
    return xids_.size();
  }
  /**
   * <code>repeated int64 xids = 3;</code>
   */
  public long getXids(int index) {
    return xids_.get(index);
  }

  public static final int DB_FIELD_NUMBER = 4;
  private long db_;
  /**
   * <code>optional uint64 db = 4;</code>
   */
  public boolean hasDb() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional uint64 db = 4;</code>
   */
  public long getDb() {
    return db_;
  }

  public static final int SEARCHNEXT_FIELD_NUMBER = 5;
  private boolean searchNext_;
  /**
   * <code>optional bool searchNext = 5;</code>
   */
  public boolean hasSearchNext() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool searchNext = 5;</code>
   */
  public boolean getSearchNext() {
    return searchNext_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, id_);
    }
    for (int i = 0; i < distances_.size(); i++) {
      output.writeFloat(2, distances_.get(i));
    }
    for (int i = 0; i < xids_.size(); i++) {
      output.writeInt64(3, xids_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt64(4, db_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(5, searchNext_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, id_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getDistancesList().size();
      size += dataSize;
      size += 1 * getDistancesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < xids_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(xids_.get(i));
      }
      size += dataSize;
      size += 1 * getXidsList().size();
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, db_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, searchNext_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.aicloud.sdk.hyena.pb.SearchResponse)) {
      return super.equals(obj);
    }
    io.aicloud.sdk.hyena.pb.SearchResponse other = (io.aicloud.sdk.hyena.pb.SearchResponse) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && getDistancesList()
        .equals(other.getDistancesList());
    result = result && getXidsList()
        .equals(other.getXidsList());
    result = result && (hasDb() == other.hasDb());
    if (hasDb()) {
      result = result && (getDb()
          == other.getDb());
    }
    result = result && (hasSearchNext() == other.hasSearchNext());
    if (hasSearchNext()) {
      result = result && (getSearchNext()
          == other.getSearchNext());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (getDistancesCount() > 0) {
      hash = (37 * hash) + DISTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getDistancesList().hashCode();
    }
    if (getXidsCount() > 0) {
      hash = (37 * hash) + XIDS_FIELD_NUMBER;
      hash = (53 * hash) + getXidsList().hashCode();
    }
    if (hasDb()) {
      hash = (37 * hash) + DB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDb());
    }
    if (hasSearchNext()) {
      hash = (37 * hash) + SEARCHNEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSearchNext());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.aicloud.sdk.hyena.pb.SearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SearchResponse search response
   * </pre>
   *
   * Protobuf type {@code rpc.SearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.SearchResponse)
      io.aicloud.sdk.hyena.pb.SearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aicloud.sdk.hyena.pb.SearchResponse.class, io.aicloud.sdk.hyena.pb.SearchResponse.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.SearchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      distances_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      xids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      db_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      searchNext_ = false;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_SearchResponse_descriptor;
    }

    public io.aicloud.sdk.hyena.pb.SearchResponse getDefaultInstanceForType() {
      return io.aicloud.sdk.hyena.pb.SearchResponse.getDefaultInstance();
    }

    public io.aicloud.sdk.hyena.pb.SearchResponse build() {
      io.aicloud.sdk.hyena.pb.SearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.aicloud.sdk.hyena.pb.SearchResponse buildPartial() {
      io.aicloud.sdk.hyena.pb.SearchResponse result = new io.aicloud.sdk.hyena.pb.SearchResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        distances_ = java.util.Collections.unmodifiableList(distances_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.distances_ = distances_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        xids_ = java.util.Collections.unmodifiableList(xids_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.xids_ = xids_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000002;
      }
      result.db_ = db_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000004;
      }
      result.searchNext_ = searchNext_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.aicloud.sdk.hyena.pb.SearchResponse) {
        return mergeFrom((io.aicloud.sdk.hyena.pb.SearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.aicloud.sdk.hyena.pb.SearchResponse other) {
      if (other == io.aicloud.sdk.hyena.pb.SearchResponse.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (!other.distances_.isEmpty()) {
        if (distances_.isEmpty()) {
          distances_ = other.distances_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDistancesIsMutable();
          distances_.addAll(other.distances_);
        }
        onChanged();
      }
      if (!other.xids_.isEmpty()) {
        if (xids_.isEmpty()) {
          xids_ = other.xids_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureXidsIsMutable();
          xids_.addAll(other.xids_);
        }
        onChanged();
      }
      if (other.hasDb()) {
        setDb(other.getDb());
      }
      if (other.hasSearchNext()) {
        setSearchNext(other.getSearchNext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.aicloud.sdk.hyena.pb.SearchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.aicloud.sdk.hyena.pb.SearchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder setId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> distances_ = java.util.Collections.emptyList();
    private void ensureDistancesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        distances_ = new java.util.ArrayList<java.lang.Float>(distances_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getDistancesList() {
      return java.util.Collections.unmodifiableList(distances_);
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public int getDistancesCount() {
      return distances_.size();
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public float getDistances(int index) {
      return distances_.get(index);
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public Builder setDistances(
        int index, float value) {
      ensureDistancesIsMutable();
      distances_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public Builder addDistances(float value) {
      ensureDistancesIsMutable();
      distances_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public Builder addAllDistances(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureDistancesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, distances_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float distances = 2;</code>
     */
    public Builder clearDistances() {
      distances_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> xids_ = java.util.Collections.emptyList();
    private void ensureXidsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        xids_ = new java.util.ArrayList<java.lang.Long>(xids_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getXidsList() {
      return java.util.Collections.unmodifiableList(xids_);
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public int getXidsCount() {
      return xids_.size();
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public long getXids(int index) {
      return xids_.get(index);
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public Builder setXids(
        int index, long value) {
      ensureXidsIsMutable();
      xids_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public Builder addXids(long value) {
      ensureXidsIsMutable();
      xids_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public Builder addAllXids(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureXidsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, xids_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 xids = 3;</code>
     */
    public Builder clearXids() {
      xids_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private long db_ ;
    /**
     * <code>optional uint64 db = 4;</code>
     */
    public boolean hasDb() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 db = 4;</code>
     */
    public long getDb() {
      return db_;
    }
    /**
     * <code>optional uint64 db = 4;</code>
     */
    public Builder setDb(long value) {
      bitField0_ |= 0x00000008;
      db_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 db = 4;</code>
     */
    public Builder clearDb() {
      bitField0_ = (bitField0_ & ~0x00000008);
      db_ = 0L;
      onChanged();
      return this;
    }

    private boolean searchNext_ ;
    /**
     * <code>optional bool searchNext = 5;</code>
     */
    public boolean hasSearchNext() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool searchNext = 5;</code>
     */
    public boolean getSearchNext() {
      return searchNext_;
    }
    /**
     * <code>optional bool searchNext = 5;</code>
     */
    public Builder setSearchNext(boolean value) {
      bitField0_ |= 0x00000010;
      searchNext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool searchNext = 5;</code>
     */
    public Builder clearSearchNext() {
      bitField0_ = (bitField0_ & ~0x00000010);
      searchNext_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.SearchResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.SearchResponse)
  private static final io.aicloud.sdk.hyena.pb.SearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.aicloud.sdk.hyena.pb.SearchResponse();
  }

  public static io.aicloud.sdk.hyena.pb.SearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
    public SearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchResponse> getParserForType() {
    return PARSER;
  }

  public io.aicloud.sdk.hyena.pb.SearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

