// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface ServerIsBusyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ServerIsBusy)
    com.google.protobuf.MessageOrBuilder {
}
