// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

/**
 * Protobuf type {@code rpc.StaleEpoch}
 */
public  final class StaleEpoch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.StaleEpoch)
    StaleEpochOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StaleEpoch.newBuilder() to construct.
  private StaleEpoch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StaleEpoch() {
    newDBs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StaleEpoch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              newDBs_ = new java.util.ArrayList<io.aicloud.sdk.hyena.pb.VectorDB>();
              mutable_bitField0_ |= 0x00000001;
            }
            newDBs_.add(
                input.readMessage(io.aicloud.sdk.hyena.pb.VectorDB.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        newDBs_ = java.util.Collections.unmodifiableList(newDBs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_StaleEpoch_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_StaleEpoch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.aicloud.sdk.hyena.pb.StaleEpoch.class, io.aicloud.sdk.hyena.pb.StaleEpoch.Builder.class);
  }

  public static final int NEWDBS_FIELD_NUMBER = 1;
  private java.util.List<io.aicloud.sdk.hyena.pb.VectorDB> newDBs_;
  /**
   * <code>repeated .meta.VectorDB newDBs = 1;</code>
   */
  public java.util.List<io.aicloud.sdk.hyena.pb.VectorDB> getNewDBsList() {
    return newDBs_;
  }
  /**
   * <code>repeated .meta.VectorDB newDBs = 1;</code>
   */
  public java.util.List<? extends io.aicloud.sdk.hyena.pb.VectorDBOrBuilder> 
      getNewDBsOrBuilderList() {
    return newDBs_;
  }
  /**
   * <code>repeated .meta.VectorDB newDBs = 1;</code>
   */
  public int getNewDBsCount() {
    return newDBs_.size();
  }
  /**
   * <code>repeated .meta.VectorDB newDBs = 1;</code>
   */
  public io.aicloud.sdk.hyena.pb.VectorDB getNewDBs(int index) {
    return newDBs_.get(index);
  }
  /**
   * <code>repeated .meta.VectorDB newDBs = 1;</code>
   */
  public io.aicloud.sdk.hyena.pb.VectorDBOrBuilder getNewDBsOrBuilder(
      int index) {
    return newDBs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < newDBs_.size(); i++) {
      output.writeMessage(1, newDBs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < newDBs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, newDBs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.aicloud.sdk.hyena.pb.StaleEpoch)) {
      return super.equals(obj);
    }
    io.aicloud.sdk.hyena.pb.StaleEpoch other = (io.aicloud.sdk.hyena.pb.StaleEpoch) obj;

    boolean result = true;
    result = result && getNewDBsList()
        .equals(other.getNewDBsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNewDBsCount() > 0) {
      hash = (37 * hash) + NEWDBS_FIELD_NUMBER;
      hash = (53 * hash) + getNewDBsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.aicloud.sdk.hyena.pb.StaleEpoch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.aicloud.sdk.hyena.pb.StaleEpoch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.StaleEpoch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.StaleEpoch)
      io.aicloud.sdk.hyena.pb.StaleEpochOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_StaleEpoch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_StaleEpoch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aicloud.sdk.hyena.pb.StaleEpoch.class, io.aicloud.sdk.hyena.pb.StaleEpoch.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.StaleEpoch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNewDBsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (newDBsBuilder_ == null) {
        newDBs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        newDBsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.aicloud.sdk.hyena.pb.HyenaRPCPB.internal_static_rpc_StaleEpoch_descriptor;
    }

    public io.aicloud.sdk.hyena.pb.StaleEpoch getDefaultInstanceForType() {
      return io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance();
    }

    public io.aicloud.sdk.hyena.pb.StaleEpoch build() {
      io.aicloud.sdk.hyena.pb.StaleEpoch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.aicloud.sdk.hyena.pb.StaleEpoch buildPartial() {
      io.aicloud.sdk.hyena.pb.StaleEpoch result = new io.aicloud.sdk.hyena.pb.StaleEpoch(this);
      int from_bitField0_ = bitField0_;
      if (newDBsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          newDBs_ = java.util.Collections.unmodifiableList(newDBs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.newDBs_ = newDBs_;
      } else {
        result.newDBs_ = newDBsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.aicloud.sdk.hyena.pb.StaleEpoch) {
        return mergeFrom((io.aicloud.sdk.hyena.pb.StaleEpoch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.aicloud.sdk.hyena.pb.StaleEpoch other) {
      if (other == io.aicloud.sdk.hyena.pb.StaleEpoch.getDefaultInstance()) return this;
      if (newDBsBuilder_ == null) {
        if (!other.newDBs_.isEmpty()) {
          if (newDBs_.isEmpty()) {
            newDBs_ = other.newDBs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNewDBsIsMutable();
            newDBs_.addAll(other.newDBs_);
          }
          onChanged();
        }
      } else {
        if (!other.newDBs_.isEmpty()) {
          if (newDBsBuilder_.isEmpty()) {
            newDBsBuilder_.dispose();
            newDBsBuilder_ = null;
            newDBs_ = other.newDBs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            newDBsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNewDBsFieldBuilder() : null;
          } else {
            newDBsBuilder_.addAllMessages(other.newDBs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.aicloud.sdk.hyena.pb.StaleEpoch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.aicloud.sdk.hyena.pb.StaleEpoch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.aicloud.sdk.hyena.pb.VectorDB> newDBs_ =
      java.util.Collections.emptyList();
    private void ensureNewDBsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        newDBs_ = new java.util.ArrayList<io.aicloud.sdk.hyena.pb.VectorDB>(newDBs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.VectorDB, io.aicloud.sdk.hyena.pb.VectorDB.Builder, io.aicloud.sdk.hyena.pb.VectorDBOrBuilder> newDBsBuilder_;

    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public java.util.List<io.aicloud.sdk.hyena.pb.VectorDB> getNewDBsList() {
      if (newDBsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newDBs_);
      } else {
        return newDBsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public int getNewDBsCount() {
      if (newDBsBuilder_ == null) {
        return newDBs_.size();
      } else {
        return newDBsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public io.aicloud.sdk.hyena.pb.VectorDB getNewDBs(int index) {
      if (newDBsBuilder_ == null) {
        return newDBs_.get(index);
      } else {
        return newDBsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder setNewDBs(
        int index, io.aicloud.sdk.hyena.pb.VectorDB value) {
      if (newDBsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewDBsIsMutable();
        newDBs_.set(index, value);
        onChanged();
      } else {
        newDBsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder setNewDBs(
        int index, io.aicloud.sdk.hyena.pb.VectorDB.Builder builderForValue) {
      if (newDBsBuilder_ == null) {
        ensureNewDBsIsMutable();
        newDBs_.set(index, builderForValue.build());
        onChanged();
      } else {
        newDBsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder addNewDBs(io.aicloud.sdk.hyena.pb.VectorDB value) {
      if (newDBsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewDBsIsMutable();
        newDBs_.add(value);
        onChanged();
      } else {
        newDBsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder addNewDBs(
        int index, io.aicloud.sdk.hyena.pb.VectorDB value) {
      if (newDBsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewDBsIsMutable();
        newDBs_.add(index, value);
        onChanged();
      } else {
        newDBsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder addNewDBs(
        io.aicloud.sdk.hyena.pb.VectorDB.Builder builderForValue) {
      if (newDBsBuilder_ == null) {
        ensureNewDBsIsMutable();
        newDBs_.add(builderForValue.build());
        onChanged();
      } else {
        newDBsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder addNewDBs(
        int index, io.aicloud.sdk.hyena.pb.VectorDB.Builder builderForValue) {
      if (newDBsBuilder_ == null) {
        ensureNewDBsIsMutable();
        newDBs_.add(index, builderForValue.build());
        onChanged();
      } else {
        newDBsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder addAllNewDBs(
        java.lang.Iterable<? extends io.aicloud.sdk.hyena.pb.VectorDB> values) {
      if (newDBsBuilder_ == null) {
        ensureNewDBsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newDBs_);
        onChanged();
      } else {
        newDBsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder clearNewDBs() {
      if (newDBsBuilder_ == null) {
        newDBs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        newDBsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public Builder removeNewDBs(int index) {
      if (newDBsBuilder_ == null) {
        ensureNewDBsIsMutable();
        newDBs_.remove(index);
        onChanged();
      } else {
        newDBsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public io.aicloud.sdk.hyena.pb.VectorDB.Builder getNewDBsBuilder(
        int index) {
      return getNewDBsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public io.aicloud.sdk.hyena.pb.VectorDBOrBuilder getNewDBsOrBuilder(
        int index) {
      if (newDBsBuilder_ == null) {
        return newDBs_.get(index);  } else {
        return newDBsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public java.util.List<? extends io.aicloud.sdk.hyena.pb.VectorDBOrBuilder> 
         getNewDBsOrBuilderList() {
      if (newDBsBuilder_ != null) {
        return newDBsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newDBs_);
      }
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public io.aicloud.sdk.hyena.pb.VectorDB.Builder addNewDBsBuilder() {
      return getNewDBsFieldBuilder().addBuilder(
          io.aicloud.sdk.hyena.pb.VectorDB.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public io.aicloud.sdk.hyena.pb.VectorDB.Builder addNewDBsBuilder(
        int index) {
      return getNewDBsFieldBuilder().addBuilder(
          index, io.aicloud.sdk.hyena.pb.VectorDB.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.VectorDB newDBs = 1;</code>
     */
    public java.util.List<io.aicloud.sdk.hyena.pb.VectorDB.Builder> 
         getNewDBsBuilderList() {
      return getNewDBsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.aicloud.sdk.hyena.pb.VectorDB, io.aicloud.sdk.hyena.pb.VectorDB.Builder, io.aicloud.sdk.hyena.pb.VectorDBOrBuilder> 
        getNewDBsFieldBuilder() {
      if (newDBsBuilder_ == null) {
        newDBsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.aicloud.sdk.hyena.pb.VectorDB, io.aicloud.sdk.hyena.pb.VectorDB.Builder, io.aicloud.sdk.hyena.pb.VectorDBOrBuilder>(
                newDBs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        newDBs_ = null;
      }
      return newDBsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.StaleEpoch)
  }

  // @@protoc_insertion_point(class_scope:rpc.StaleEpoch)
  private static final io.aicloud.sdk.hyena.pb.StaleEpoch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.aicloud.sdk.hyena.pb.StaleEpoch();
  }

  public static io.aicloud.sdk.hyena.pb.StaleEpoch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<StaleEpoch>
      PARSER = new com.google.protobuf.AbstractParser<StaleEpoch>() {
    public StaleEpoch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StaleEpoch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StaleEpoch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StaleEpoch> getParserForType() {
    return PARSER;
  }

  public io.aicloud.sdk.hyena.pb.StaleEpoch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

