// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * Store container of vectordb
 * </pre>
 *
 * Protobuf type {@code meta.Store}
 */
public  final class Store extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meta.Store)
    StoreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Store.newBuilder() to construct.
  private Store(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Store() {
    id_ = 0L;
    address_ = "";
    clientAddress_ = "";
    lables_ = java.util.Collections.emptyList();
    state_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Store(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readUInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            address_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            clientAddress_ = bs;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              lables_ = new java.util.ArrayList<Label>();
              mutable_bitField0_ |= 0x00000008;
            }
            lables_.add(
                input.readMessage(Label.PARSER, extensionRegistry));
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
            StoreState value = StoreState.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(5, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              state_ = rawValue;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        lables_ = java.util.Collections.unmodifiableList(lables_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HyenaMetaPB.internal_static_meta_Store_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HyenaMetaPB.internal_static_meta_Store_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Store.class, Store.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private volatile Object address_;
  /**
   * <code>optional string address = 2;</code>
   */
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string address = 2;</code>
   */
  public String getAddress() {
    Object ref = address_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAddressBytes() {
    Object ref = address_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTADDRESS_FIELD_NUMBER = 3;
  private volatile Object clientAddress_;
  /**
   * <code>optional string clientAddress = 3;</code>
   */
  public boolean hasClientAddress() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string clientAddress = 3;</code>
   */
  public String getClientAddress() {
    Object ref = clientAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        clientAddress_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string clientAddress = 3;</code>
   */
  public com.google.protobuf.ByteString
      getClientAddressBytes() {
    Object ref = clientAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABLES_FIELD_NUMBER = 4;
  private java.util.List<Label> lables_;
  /**
   * <code>repeated .meta.Label lables = 4;</code>
   */
  public java.util.List<Label> getLablesList() {
    return lables_;
  }
  /**
   * <code>repeated .meta.Label lables = 4;</code>
   */
  public java.util.List<? extends LabelOrBuilder>
      getLablesOrBuilderList() {
    return lables_;
  }
  /**
   * <code>repeated .meta.Label lables = 4;</code>
   */
  public int getLablesCount() {
    return lables_.size();
  }
  /**
   * <code>repeated .meta.Label lables = 4;</code>
   */
  public Label getLables(int index) {
    return lables_.get(index);
  }
  /**
   * <code>repeated .meta.Label lables = 4;</code>
   */
  public LabelOrBuilder getLablesOrBuilder(
      int index) {
    return lables_.get(index);
  }

  public static final int STATE_FIELD_NUMBER = 5;
  private int state_;
  /**
   * <code>optional .meta.StoreState state = 5;</code>
   */
  public boolean hasState() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .meta.StoreState state = 5;</code>
   */
  public StoreState getState() {
    StoreState result = StoreState.valueOf(state_);
    return result == null ? StoreState.UP : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientAddress_);
    }
    for (int i = 0; i < lables_.size(); i++) {
      output.writeMessage(4, lables_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeEnum(5, state_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientAddress_);
    }
    for (int i = 0; i < lables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, lables_.get(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, state_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Store)) {
      return super.equals(obj);
    }
    Store other = (Store) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && (getId()
          == other.getId());
    }
    result = result && (hasAddress() == other.hasAddress());
    if (hasAddress()) {
      result = result && getAddress()
          .equals(other.getAddress());
    }
    result = result && (hasClientAddress() == other.hasClientAddress());
    if (hasClientAddress()) {
      result = result && getClientAddress()
          .equals(other.getClientAddress());
    }
    result = result && getLablesList()
        .equals(other.getLablesList());
    result = result && (hasState() == other.hasState());
    if (hasState()) {
      result = result && state_ == other.state_;
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasClientAddress()) {
      hash = (37 * hash) + CLIENTADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getClientAddress().hashCode();
    }
    if (getLablesCount() > 0) {
      hash = (37 * hash) + LABLES_FIELD_NUMBER;
      hash = (53 * hash) + getLablesList().hashCode();
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Store parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Store parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Store parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Store parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Store parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Store parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Store parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Store parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Store parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Store parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Store parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Store parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Store prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Store container of vectordb
   * </pre>
   *
   * Protobuf type {@code meta.Store}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.Store)
      StoreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HyenaMetaPB.internal_static_meta_Store_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HyenaMetaPB.internal_static_meta_Store_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Store.class, Store.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.Store.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLablesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      clientAddress_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (lablesBuilder_ == null) {
        lables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        lablesBuilder_.clear();
      }
      state_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HyenaMetaPB.internal_static_meta_Store_descriptor;
    }

    public Store getDefaultInstanceForType() {
      return Store.getDefaultInstance();
    }

    public Store build() {
      Store result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Store buildPartial() {
      Store result = new Store(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.address_ = address_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.clientAddress_ = clientAddress_;
      if (lablesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          lables_ = java.util.Collections.unmodifiableList(lables_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lables_ = lables_;
      } else {
        result.lables_ = lablesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000008;
      }
      result.state_ = state_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Store) {
        return mergeFrom((Store)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Store other) {
      if (other == Store.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000002;
        address_ = other.address_;
        onChanged();
      }
      if (other.hasClientAddress()) {
        bitField0_ |= 0x00000004;
        clientAddress_ = other.clientAddress_;
        onChanged();
      }
      if (lablesBuilder_ == null) {
        if (!other.lables_.isEmpty()) {
          if (lables_.isEmpty()) {
            lables_ = other.lables_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLablesIsMutable();
            lables_.addAll(other.lables_);
          }
          onChanged();
        }
      } else {
        if (!other.lables_.isEmpty()) {
          if (lablesBuilder_.isEmpty()) {
            lablesBuilder_.dispose();
            lablesBuilder_ = null;
            lables_ = other.lables_;
            bitField0_ = (bitField0_ & ~0x00000008);
            lablesBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLablesFieldBuilder() : null;
          } else {
            lablesBuilder_.addAllMessages(other.lables_);
          }
        }
      }
      if (other.hasState()) {
        setState(other.getState());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Store parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Store) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private Object address_ = "";
    /**
     * <code>optional string address = 2;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public Builder setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000002);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      address_ = value;
      onChanged();
      return this;
    }

    private Object clientAddress_ = "";
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public boolean hasClientAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public String getClientAddress() {
      Object ref = clientAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientAddress_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientAddressBytes() {
      Object ref = clientAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public Builder setClientAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      clientAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public Builder clearClientAddress() {
      bitField0_ = (bitField0_ & ~0x00000004);
      clientAddress_ = getDefaultInstance().getClientAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string clientAddress = 3;</code>
     */
    public Builder setClientAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      clientAddress_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Label> lables_ =
      java.util.Collections.emptyList();
    private void ensureLablesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        lables_ = new java.util.ArrayList<Label>(lables_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Label, Label.Builder, LabelOrBuilder> lablesBuilder_;

    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public java.util.List<Label> getLablesList() {
      if (lablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lables_);
      } else {
        return lablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public int getLablesCount() {
      if (lablesBuilder_ == null) {
        return lables_.size();
      } else {
        return lablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Label getLables(int index) {
      if (lablesBuilder_ == null) {
        return lables_.get(index);
      } else {
        return lablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder setLables(
        int index, Label value) {
      if (lablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLablesIsMutable();
        lables_.set(index, value);
        onChanged();
      } else {
        lablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder setLables(
        int index, Label.Builder builderForValue) {
      if (lablesBuilder_ == null) {
        ensureLablesIsMutable();
        lables_.set(index, builderForValue.build());
        onChanged();
      } else {
        lablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder addLables(Label value) {
      if (lablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLablesIsMutable();
        lables_.add(value);
        onChanged();
      } else {
        lablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder addLables(
        int index, Label value) {
      if (lablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLablesIsMutable();
        lables_.add(index, value);
        onChanged();
      } else {
        lablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder addLables(
        Label.Builder builderForValue) {
      if (lablesBuilder_ == null) {
        ensureLablesIsMutable();
        lables_.add(builderForValue.build());
        onChanged();
      } else {
        lablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder addLables(
        int index, Label.Builder builderForValue) {
      if (lablesBuilder_ == null) {
        ensureLablesIsMutable();
        lables_.add(index, builderForValue.build());
        onChanged();
      } else {
        lablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder addAllLables(
        Iterable<? extends Label> values) {
      if (lablesBuilder_ == null) {
        ensureLablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lables_);
        onChanged();
      } else {
        lablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder clearLables() {
      if (lablesBuilder_ == null) {
        lables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        lablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Builder removeLables(int index) {
      if (lablesBuilder_ == null) {
        ensureLablesIsMutable();
        lables_.remove(index);
        onChanged();
      } else {
        lablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Label.Builder getLablesBuilder(
        int index) {
      return getLablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public LabelOrBuilder getLablesOrBuilder(
        int index) {
      if (lablesBuilder_ == null) {
        return lables_.get(index);  } else {
        return lablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public java.util.List<? extends LabelOrBuilder>
         getLablesOrBuilderList() {
      if (lablesBuilder_ != null) {
        return lablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lables_);
      }
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Label.Builder addLablesBuilder() {
      return getLablesFieldBuilder().addBuilder(
          Label.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public Label.Builder addLablesBuilder(
        int index) {
      return getLablesFieldBuilder().addBuilder(
          index, Label.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.Label lables = 4;</code>
     */
    public java.util.List<Label.Builder>
         getLablesBuilderList() {
      return getLablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Label, Label.Builder, LabelOrBuilder>
        getLablesFieldBuilder() {
      if (lablesBuilder_ == null) {
        lablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Label, Label.Builder, LabelOrBuilder>(
                lables_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        lables_ = null;
      }
      return lablesBuilder_;
    }

    private int state_ = 0;
    /**
     * <code>optional .meta.StoreState state = 5;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .meta.StoreState state = 5;</code>
     */
    public StoreState getState() {
      StoreState result = StoreState.valueOf(state_);
      return result == null ? StoreState.UP : result;
    }
    /**
     * <code>optional .meta.StoreState state = 5;</code>
     */
    public Builder setState(StoreState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .meta.StoreState state = 5;</code>
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000010);
      state_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meta.Store)
  }

  // @@protoc_insertion_point(class_scope:meta.Store)
  private static final Store DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Store();
  }

  public static Store getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<Store>
      PARSER = new com.google.protobuf.AbstractParser<Store>() {
    public Store parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Store(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Store> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Store> getParserForType() {
    return PARSER;
  }

  public Store getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

