// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * StoreState store state
 * </pre>
 *
 * Protobuf enum {@code meta.StoreState}
 */
public enum StoreState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UP = 0;</code>
   */
  UP(0),
  /**
   * <code>Down = 1;</code>
   */
  Down(1),
  /**
   * <code>Tombstone = 2;</code>
   */
  Tombstone(2),
  ;

  /**
   * <code>UP = 0;</code>
   */
  public static final int UP_VALUE = 0;
  /**
   * <code>Down = 1;</code>
   */
  public static final int Down_VALUE = 1;
  /**
   * <code>Tombstone = 2;</code>
   */
  public static final int Tombstone_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static StoreState valueOf(int value) {
    return forNumber(value);
  }

  public static StoreState forNumber(int value) {
    switch (value) {
      case 0: return UP;
      case 1: return Down;
      case 2: return Tombstone;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StoreState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StoreState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StoreState>() {
          public StoreState findValueByNumber(int number) {
            return StoreState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return HyenaMetaPB.getDescriptor().getEnumTypes().get(0);
  }

  private static final StoreState[] VALUES = values();

  public static StoreState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StoreState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:meta.StoreState)
}

