// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.aicloud.sdk.hyena.pb;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>optional uint64 db = 2;</code>
   */
  boolean hasDb();
  /**
   * <code>optional uint64 db = 2;</code>
   */
  long getDb();

  /**
   * <code>repeated float xbs = 3;</code>
   */
  java.util.List<java.lang.Float> getXbsList();
  /**
   * <code>repeated float xbs = 3;</code>
   */
  int getXbsCount();
  /**
   * <code>repeated float xbs = 3;</code>
   */
  float getXbs(int index);

  /**
   * <code>repeated int64 ids = 4;</code>
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated int64 ids = 4;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated int64 ids = 4;</code>
   */
  long getIds(int index);
}
