// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

public interface VectorDBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.VectorDB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional .meta.DBState state = 2;</code>
   */
  boolean hasState();
  /**
   * <code>optional .meta.DBState state = 2;</code>
   */
  io.aicloud.sdk.hyena.pb.DBState getState();

  /**
   * <code>optional uint64 start = 3;</code>
   */
  boolean hasStart();
  /**
   * <code>optional uint64 start = 3;</code>
   */
  long getStart();

  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  boolean hasEpoch();
  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  io.aicloud.sdk.hyena.pb.Epoch getEpoch();
  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  io.aicloud.sdk.hyena.pb.EpochOrBuilder getEpochOrBuilder();

  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  java.util.List<io.aicloud.sdk.hyena.pb.Peer> 
      getPeersList();
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  io.aicloud.sdk.hyena.pb.Peer getPeers(int index);
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  int getPeersCount();
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  java.util.List<? extends io.aicloud.sdk.hyena.pb.PeerOrBuilder> 
      getPeersOrBuilderList();
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  io.aicloud.sdk.hyena.pb.PeerOrBuilder getPeersOrBuilder(
      int index);
}
