// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package io.aicloud.sdk.hyena.pb;

/**
 * <pre>
 * VectorDB is a vectorDB
 * </pre>
 *
 * Protobuf type {@code meta.VectorDB}
 */
public  final class VectorDB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meta.VectorDB)
    VectorDBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VectorDB.newBuilder() to construct.
  private VectorDB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VectorDB() {
    id_ = 0L;
    state_ = 0;
    start_ = 0L;
    peers_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VectorDB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            DBState value = DBState.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              state_ = rawValue;
            }
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            start_ = input.readUInt64();
            break;
          }
          case 34: {
            Epoch.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = epoch_.toBuilder();
            }
            epoch_ = input.readMessage(Epoch.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(epoch_);
              epoch_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              peers_ = new java.util.ArrayList<Peer>();
              mutable_bitField0_ |= 0x00000010;
            }
            peers_.add(
                input.readMessage(Peer.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        peers_ = java.util.Collections.unmodifiableList(peers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HyenaMetaPB.internal_static_meta_VectorDB_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HyenaMetaPB.internal_static_meta_VectorDB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VectorDB.class, VectorDB.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_;
  /**
   * <code>optional .meta.DBState state = 2;</code>
   */
  public boolean hasState() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .meta.DBState state = 2;</code>
   */
  public DBState getState() {
    DBState result = DBState.valueOf(state_);
    return result == null ? DBState.RU : result;
  }

  public static final int START_FIELD_NUMBER = 3;
  private long start_;
  /**
   * <code>optional uint64 start = 3;</code>
   */
  public boolean hasStart() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional uint64 start = 3;</code>
   */
  public long getStart() {
    return start_;
  }

  public static final int EPOCH_FIELD_NUMBER = 4;
  private Epoch epoch_;
  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  public boolean hasEpoch() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  public Epoch getEpoch() {
    return epoch_ == null ? Epoch.getDefaultInstance() : epoch_;
  }
  /**
   * <code>optional .meta.Epoch epoch = 4;</code>
   */
  public EpochOrBuilder getEpochOrBuilder() {
    return epoch_ == null ? Epoch.getDefaultInstance() : epoch_;
  }

  public static final int PEERS_FIELD_NUMBER = 5;
  private java.util.List<Peer> peers_;
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  public java.util.List<Peer> getPeersList() {
    return peers_;
  }
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  public java.util.List<? extends PeerOrBuilder>
      getPeersOrBuilderList() {
    return peers_;
  }
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  public int getPeersCount() {
    return peers_.size();
  }
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  public Peer getPeers(int index) {
    return peers_.get(index);
  }
  /**
   * <code>repeated .meta.Peer peers = 5;</code>
   */
  public PeerOrBuilder getPeersOrBuilder(
      int index) {
    return peers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, state_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt64(3, start_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getEpoch());
    }
    for (int i = 0; i < peers_.size(); i++) {
      output.writeMessage(5, peers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, start_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEpoch());
    }
    for (int i = 0; i < peers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, peers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VectorDB)) {
      return super.equals(obj);
    }
    VectorDB other = (VectorDB) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && (getId()
          == other.getId());
    }
    result = result && (hasState() == other.hasState());
    if (hasState()) {
      result = result && state_ == other.state_;
    }
    result = result && (hasStart() == other.hasStart());
    if (hasStart()) {
      result = result && (getStart()
          == other.getStart());
    }
    result = result && (hasEpoch() == other.hasEpoch());
    if (hasEpoch()) {
      result = result && getEpoch()
          .equals(other.getEpoch());
    }
    result = result && getPeersList()
        .equals(other.getPeersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
    }
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStart());
    }
    if (hasEpoch()) {
      hash = (37 * hash) + EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + getEpoch().hashCode();
    }
    if (getPeersCount() > 0) {
      hash = (37 * hash) + PEERS_FIELD_NUMBER;
      hash = (53 * hash) + getPeersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VectorDB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorDB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorDB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorDB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorDB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VectorDB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VectorDB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VectorDB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VectorDB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VectorDB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VectorDB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VectorDB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VectorDB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * VectorDB is a vectorDB
   * </pre>
   *
   * Protobuf type {@code meta.VectorDB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.VectorDB)
      VectorDBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HyenaMetaPB.internal_static_meta_VectorDB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HyenaMetaPB.internal_static_meta_VectorDB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VectorDB.class, VectorDB.Builder.class);
    }

    // Construct using io.aicloud.sdk.hyena.pb.VectorDB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEpochFieldBuilder();
        getPeersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      state_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      start_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (epochBuilder_ == null) {
        epoch_ = null;
      } else {
        epochBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (peersBuilder_ == null) {
        peers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        peersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HyenaMetaPB.internal_static_meta_VectorDB_descriptor;
    }

    public VectorDB getDefaultInstanceForType() {
      return VectorDB.getDefaultInstance();
    }

    public VectorDB build() {
      VectorDB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public VectorDB buildPartial() {
      VectorDB result = new VectorDB(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.state_ = state_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.start_ = start_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (epochBuilder_ == null) {
        result.epoch_ = epoch_;
      } else {
        result.epoch_ = epochBuilder_.build();
      }
      if (peersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          peers_ = java.util.Collections.unmodifiableList(peers_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.peers_ = peers_;
      } else {
        result.peers_ = peersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VectorDB) {
        return mergeFrom((VectorDB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VectorDB other) {
      if (other == VectorDB.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasState()) {
        setState(other.getState());
      }
      if (other.hasStart()) {
        setStart(other.getStart());
      }
      if (other.hasEpoch()) {
        mergeEpoch(other.getEpoch());
      }
      if (peersBuilder_ == null) {
        if (!other.peers_.isEmpty()) {
          if (peers_.isEmpty()) {
            peers_ = other.peers_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePeersIsMutable();
            peers_.addAll(other.peers_);
          }
          onChanged();
        }
      } else {
        if (!other.peers_.isEmpty()) {
          if (peersBuilder_.isEmpty()) {
            peersBuilder_.dispose();
            peersBuilder_ = null;
            peers_ = other.peers_;
            bitField0_ = (bitField0_ & ~0x00000010);
            peersBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeersFieldBuilder() : null;
          } else {
            peersBuilder_.addAllMessages(other.peers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VectorDB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VectorDB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>optional .meta.DBState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .meta.DBState state = 2;</code>
     */
    public DBState getState() {
      DBState result = DBState.valueOf(state_);
      return result == null ? DBState.RU : result;
    }
    /**
     * <code>optional .meta.DBState state = 2;</code>
     */
    public Builder setState(DBState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .meta.DBState state = 2;</code>
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      state_ = 0;
      onChanged();
      return this;
    }

    private long start_ ;
    /**
     * <code>optional uint64 start = 3;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 start = 3;</code>
     */
    public long getStart() {
      return start_;
    }
    /**
     * <code>optional uint64 start = 3;</code>
     */
    public Builder setStart(long value) {
      bitField0_ |= 0x00000004;
      start_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 start = 3;</code>
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000004);
      start_ = 0L;
      onChanged();
      return this;
    }

    private Epoch epoch_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Epoch, Epoch.Builder, EpochOrBuilder> epochBuilder_;
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public boolean hasEpoch() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Epoch getEpoch() {
      if (epochBuilder_ == null) {
        return epoch_ == null ? Epoch.getDefaultInstance() : epoch_;
      } else {
        return epochBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Builder setEpoch(Epoch value) {
      if (epochBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        epoch_ = value;
        onChanged();
      } else {
        epochBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Builder setEpoch(
        Epoch.Builder builderForValue) {
      if (epochBuilder_ == null) {
        epoch_ = builderForValue.build();
        onChanged();
      } else {
        epochBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Builder mergeEpoch(Epoch value) {
      if (epochBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            epoch_ != null &&
            epoch_ != Epoch.getDefaultInstance()) {
          epoch_ =
            Epoch.newBuilder(epoch_).mergeFrom(value).buildPartial();
        } else {
          epoch_ = value;
        }
        onChanged();
      } else {
        epochBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Builder clearEpoch() {
      if (epochBuilder_ == null) {
        epoch_ = null;
        onChanged();
      } else {
        epochBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public Epoch.Builder getEpochBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEpochFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    public EpochOrBuilder getEpochOrBuilder() {
      if (epochBuilder_ != null) {
        return epochBuilder_.getMessageOrBuilder();
      } else {
        return epoch_ == null ?
            Epoch.getDefaultInstance() : epoch_;
      }
    }
    /**
     * <code>optional .meta.Epoch epoch = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Epoch, Epoch.Builder, EpochOrBuilder>
        getEpochFieldBuilder() {
      if (epochBuilder_ == null) {
        epochBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Epoch, Epoch.Builder, EpochOrBuilder>(
                getEpoch(),
                getParentForChildren(),
                isClean());
        epoch_ = null;
      }
      return epochBuilder_;
    }

    private java.util.List<Peer> peers_ =
      java.util.Collections.emptyList();
    private void ensurePeersIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        peers_ = new java.util.ArrayList<Peer>(peers_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Peer, Peer.Builder, PeerOrBuilder> peersBuilder_;

    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public java.util.List<Peer> getPeersList() {
      if (peersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peers_);
      } else {
        return peersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public int getPeersCount() {
      if (peersBuilder_ == null) {
        return peers_.size();
      } else {
        return peersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Peer getPeers(int index) {
      if (peersBuilder_ == null) {
        return peers_.get(index);
      } else {
        return peersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder setPeers(
        int index, Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.set(index, value);
        onChanged();
      } else {
        peersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder setPeers(
        int index, Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.set(index, builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder addPeers(Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.add(value);
        onChanged();
      } else {
        peersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder addPeers(
        int index, Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.add(index, value);
        onChanged();
      } else {
        peersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder addPeers(
        Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.add(builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder addPeers(
        int index, Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.add(index, builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder addAllPeers(
        Iterable<? extends Peer> values) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peers_);
        onChanged();
      } else {
        peersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder clearPeers() {
      if (peersBuilder_ == null) {
        peers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        peersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Builder removePeers(int index) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.remove(index);
        onChanged();
      } else {
        peersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Peer.Builder getPeersBuilder(
        int index) {
      return getPeersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public PeerOrBuilder getPeersOrBuilder(
        int index) {
      if (peersBuilder_ == null) {
        return peers_.get(index);  } else {
        return peersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public java.util.List<? extends PeerOrBuilder>
         getPeersOrBuilderList() {
      if (peersBuilder_ != null) {
        return peersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peers_);
      }
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Peer.Builder addPeersBuilder() {
      return getPeersFieldBuilder().addBuilder(
          Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public Peer.Builder addPeersBuilder(
        int index) {
      return getPeersFieldBuilder().addBuilder(
          index, Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.Peer peers = 5;</code>
     */
    public java.util.List<Peer.Builder>
         getPeersBuilderList() {
      return getPeersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Peer, Peer.Builder, PeerOrBuilder>
        getPeersFieldBuilder() {
      if (peersBuilder_ == null) {
        peersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Peer, Peer.Builder, PeerOrBuilder>(
                peers_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        peers_ = null;
      }
      return peersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meta.VectorDB)
  }

  // @@protoc_insertion_point(class_scope:meta.VectorDB)
  private static final VectorDB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VectorDB();
  }

  public static VectorDB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<VectorDB>
      PARSER = new com.google.protobuf.AbstractParser<VectorDB>() {
    public VectorDB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VectorDB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VectorDB> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VectorDB> getParserForType() {
    return PARSER;
  }

  public VectorDB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

